version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-linkedin:/var/lib/postgresql/data

  postgres_admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
    postgres-linkedin:
