export enum FriendRequestStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  NOT_SENT = 'NOT_SENT',
  WAITING_CURRENT_USER_RESPONSE = 'WAITING_CURRENT_USER_RESPONSE',
}
